import { User, Listing, BookingRequest } from "./types";

// ── Mock Users ──────────────────────────────────────────────
export const mockUsers: User[] = [
  {
    id: "venue-1",
    role: "venue",
    name: "Luxe Hair Studio",
    email: "info@luxehairstudio.com",
    verified: true,
    avatarUrl: undefined,
  },
  {
    id: "venue-2",
    role: "venue",
    name: "The Beauty Collective",
    email: "hello@beautycollective.com",
    verified: true,
    avatarUrl: undefined,
  },
  {
    id: "renter-1",
    role: "renter",
    name: "Sarah Johnson",
    email: "sarah@email.com",
    verified: true,
    avatarUrl: undefined,
  },
  {
    id: "renter-2",
    role: "renter",
    name: "Marcus Lee",
    email: "marcus@email.com",
    verified: true,
    avatarUrl: undefined,
  },
  {
    id: "renter-3",
    role: "renter",
    name: "Priya Patel",
    email: "priya@email.com",
    verified: false,
    avatarUrl: undefined,
  },
];

// ── Mock Listings ───────────────────────────────────────────
export const mockListings: Listing[] = [
  {
    id: "listing-1",
    venueId: "venue-1",
    venueName: "Luxe Hair Studio",
    title: "Premium Styling Chair — Central London",
    description:
      "A fully equipped styling station in our modern Shoreditch salon. Includes mirror, storage, and access to wash basins. Perfect for an experienced stylist looking for a professional space to see clients.",
    priceType: "flat",
    price: 150,
    location: "Shoreditch, London",
    availability: "Mon–Fri, 9am–6pm",
    equipmentIncluded: ["Mirror", "Styling chair", "Storage unit", "Wash basin access"],
    imageUrl: "/images/listing-1.jpg",
    rating: 4.8,
    createdAt: "2026-01-15",
  },
  {
    id: "listing-2",
    venueId: "venue-1",
    venueName: "Luxe Hair Studio",
    title: "Barber Station with Full Kit",
    description:
      "Dedicated barber station in a busy salon with steady foot traffic. Comes with clippers, scissors, and all essential tools. Great visibility and walk-in potential.",
    priceType: "flat",
    price: 120,
    location: "Shoreditch, London",
    availability: "Mon–Sat, 8am–7pm",
    equipmentIncluded: ["Barber chair", "Clippers", "Scissors", "Mirror", "Towels"],
    imageUrl: "/images/listing-2.jpg",
    rating: 4.5,
    createdAt: "2026-01-20",
  },
  {
    id: "listing-3",
    venueId: "venue-2",
    venueName: "The Beauty Collective",
    title: "Nail Tech Station — Covent Garden",
    description:
      "Bright, clean nail station in a trendy Covent Garden beauty bar. Ideal for a nail technician who wants to work independently in a high-traffic area. All ventilation and lighting provided.",
    priceType: "flat",
    price: 90,
    location: "Covent Garden, London",
    availability: "Tue–Sat, 10am–7pm",
    equipmentIncluded: ["Nail desk", "LED lamp", "Ventilation", "Storage drawers"],
    imageUrl: "/images/listing-3.jpg",
    rating: 4.9,
    createdAt: "2026-02-01",
  },
  {
    id: "listing-4",
    venueId: "venue-2",
    venueName: "The Beauty Collective",
    title: "Beauty Treatment Room — Private",
    description:
      "A private treatment room perfect for lash techs, facialists, or massage therapists. Soundproofed with adjustable lighting. Book by the day or week.",
    priceType: "flat",
    price: 200,
    location: "Covent Garden, London",
    availability: "Mon–Sun, 9am–9pm",
    equipmentIncluded: ["Treatment bed", "Adjustable lighting", "Sink", "Towel warmer"],
    imageUrl: "/images/listing-4.jpg",
    rating: 4.7,
    createdAt: "2026-02-05",
  },
  {
    id: "listing-5",
    venueId: "venue-1",
    venueName: "Luxe Hair Studio",
    title: "Colour Station with Basin",
    description:
      "Spacious colouring station with dedicated wash basin. Ideal for colour specialists who need extra space and water access. Located in a vibrant, professional environment.",
    priceType: "commission",
    price: 100,
    location: "Shoreditch, London",
    availability: "Wed–Sun, 9am–5pm",
    equipmentIncluded: ["Wash basin", "Colour trolley", "Mirror", "Styling chair"],
    imageUrl: "/images/listing-5.jpg",
    rating: 4.6,
    createdAt: "2026-02-10",
  },
  {
    id: "listing-6",
    venueId: "venue-2",
    venueName: "The Beauty Collective",
    title: "Makeup Artist Station",
    description:
      "Well-lit makeup station with professional mirror and ample counter space. Located in a busy beauty bar with great natural lighting. Perfect for freelance MUAs.",
    priceType: "flat",
    price: 110,
    location: "Covent Garden, London",
    availability: "Mon–Fri, 8am–6pm",
    equipmentIncluded: ["Lighted mirror", "Counter space", "Storage", "Stool"],
    imageUrl: "/images/listing-6.jpg",
    rating: 4.4,
    createdAt: "2026-02-12",
  },
];

// ── Mock Booking Requests ───────────────────────────────────
export const mockBookingRequests: BookingRequest[] = [
  {
    id: "booking-1",
    listingId: "listing-1",
    listingTitle: "Premium Styling Chair — Central London",
    renterId: "renter-1",
    renterName: "Sarah Johnson",
    startDate: "2026-03-01",
    endDate: "2026-03-07",
    status: "approved",
    createdAt: "2026-02-10",
  },
  {
    id: "booking-2",
    listingId: "listing-3",
    listingTitle: "Nail Tech Station — Covent Garden",
    renterId: "renter-1",
    renterName: "Sarah Johnson",
    startDate: "2026-03-10",
    endDate: "2026-03-14",
    status: "pending",
    createdAt: "2026-02-12",
  },
  {
    id: "booking-3",
    listingId: "listing-2",
    listingTitle: "Barber Station with Full Kit",
    renterId: "renter-2",
    renterName: "Marcus Lee",
    startDate: "2026-03-05",
    endDate: "2026-03-12",
    status: "pending",
    createdAt: "2026-02-11",
  },
  {
    id: "booking-4",
    listingId: "listing-4",
    listingTitle: "Beauty Treatment Room — Private",
    renterId: "renter-3",
    renterName: "Priya Patel",
    startDate: "2026-03-15",
    endDate: "2026-03-20",
    status: "declined",
    createdAt: "2026-02-13",
  },
];
